import { NextResponse } from "next/server";
import { getRiskModel } from "@/lib/engine/ml";
import { MODEL_VERSION, RISK_MODEL_VERSION } from "@/lib/engine/domain";
import { SIMULATION_CONFIG, PLANNER_CONFIG, FEES } from "@/lib/engine/sathiConfig";
import { getForecaster } from "@/lib/engine/forecaster";
import evalJson from "@/data/eval.json";

export const dynamic = "force-dynamic";

/**
 * Model card (reference: GET /v1/benchmark + /v1/meta/model-card): the
 * responsible-AI documentation for the models behind the product — now
 * including the merged irregular-flow quantile forecaster (ML handoff).
 */
export async function GET() {
  let metrics: ReturnType<typeof getRiskModel>["metrics"] | null = null;
  try {
    metrics = getRiskModel().metrics;
  } catch {
    metrics = null;
  }
  const fc = getForecaster();
  const evalData = evalJson as Record<string, unknown>;

  return NextResponse.json({
    model_card: {
      details: {
        product: "Sathi (সাথী) — AI financial copilot for upay",
        risk_model: {
          architecture: "Logistic regression (L2, deterministic full-batch GD)",
          version: RISK_MODEL_VERSION,
          objective: "Predict P(balance dips below the essential-spend safety line within 7 days)",
          features: "leakage-safe trailing aggregates + calendar facts (see /api/metrics coefficients)",
        },
        forecast: fc
          ? {
              architecture: "LightGBM quantile ensemble (9 quantiles, pinball loss, direct multi-horizon 1–35 days) + recurring-stream detection + block-correlated calibrated path simulation",
              version: fc.version,
              objective: "Daily irregular net-flow quantiles; wallet paths give P(shortfall) before the next income, trough day, daily p10/p50/p90 bands and the model-based safe-to-spend",
              inputs: "Only the user's own transactions dated on or before the forecast origin — no persona label, persona configuration, ground truth or user id is ever used as a feature",
              calibration: "split-conformal widening (CQR) + within-week path correlation fitted on held-out calibration users only; P(shortfall) Platt-recalibrated",
              trained_by: "ml/ pipeline (python -m ml.train); artifacts in web/ml-artifacts/forecast/ — the TypeScript predictor is bit-identical to the Python booster (web/tests/fixtures/lgb-predictions.json)",
            }
          : {
              architecture: "Day-of-month seasonal baseline + seeded stationary block bootstrap (5-day blocks, 400 paths)",
              version: `${MODEL_VERSION}+bootstrap-sim`,
              objective: "Daily balance quantiles (p10/p50/p90) and P(shortfall) before the next income",
            },
        goal_planner: {
          architecture: `Monte Carlo over the user's own surplus distribution (${PLANNER_CONFIG.n_simulations} paths, common random numbers) + Platt recalibration of P(goal met) (a=${PLANNER_CONFIG.calibration_a}, b=${PLANNER_CONFIG.calibration_b}) fitted on the frozen T6 back-test — the raw i.i.d. simulation is ~3-5x optimistic`,
          objective: "P(goal met) with Wilson 95% intervals for three honest option types",
        },
      },
      intended_use: {
        primary: "Short-term liquidity pressure awareness for mobile-wallet users in Bangladesh.",
        informational_only:
          "Sathi never automates funds movement, never approves or denies credit, and never nudges spending. Options are presented with trade-offs — never commanded.",
        explainability: "Every insight carries an evidence block (data window, model versions, assumptions, labels).",
      },
      evaluation: fc
        ? {
            forecaster: {
              label: evalData.label,
              model_version: evalData.model_version,
              n_test_users: evalData.n_test_users,
              note: "All tables T1–T7 are generated by python -m ml.evaluate from the frozen held-out test users; see docs/eval_report.md — numbers are never copied by hand.",
              endpoint: "/api/v1/me/benchmark",
            },
            in_app_classifier: metrics
              ? {
                  brier: { ml: metrics.ml.brier, rule_baseline: metrics.ruleBaseline.brier },
                  brier_skill_score_vs_rule: metrics.brierSkillScoreVsRule,
                  brier_skill_score_vs_climatology: metrics.brierSkillScoreVsClimatology,
                  pr_auc: { ml: metrics.ml.prAuc, rule_baseline: metrics.ruleBaseline.prAuc },
                  roc_auc: { ml: metrics.ml.auc, rule_baseline: metrics.ruleBaseline.auc },
                  tested_on: metrics.testedOn,
                }
              : { note: "model training unavailable in this process" },
          }
        : metrics
          ? {
              brier: { ml: metrics.ml.brier, rule_baseline: metrics.ruleBaseline.brier },
              brier_skill_score_vs_rule: metrics.brierSkillScoreVsRule,
              brier_skill_score_vs_climatology: metrics.brierSkillScoreVsClimatology,
              pr_auc: { ml: metrics.ml.prAuc, rule_baseline: metrics.ruleBaseline.prAuc },
              roc_auc: { ml: metrics.ml.auc, rule_baseline: metrics.ruleBaseline.auc },
              tested_on: metrics.testedOn,
            }
          : { note: "model training unavailable in this process" },
      ethical_safeguards: {
        fail_closed_validator:
          "LLM text is constrained by a numeric validator (llmSafety.ts). Any number not grounded in engine output causes immediate fallback to reviewed bilingual templates.",
        prompt_sanitizer: "Adversarial and money-movement intents are refused before any model sees them.",
        privacy_by_design:
          "Zero production PII; all training data is deterministic synthetic generation from documented persona assumptions.",
        assumptions_surfaced: `Fee math uses the labelled illustrative rate of ${FEES.cash_out_bps} bps (min ৳${FEES.cash_out_min_paisa / 100}).`,
      },
      simulation_config: SIMULATION_CONFIG,
    },
  });
}
